"""Create recipe table

Revision ID: b6754b7c73af
Revises: e4adb7594bca
Create Date: 2025-01-08 00:20:31.919898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6754b7c73af'
down_revision = 'e4adb7594bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
